Test_Technique/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('asteroïd/', include('asteroïd.urls')),
    path('admin/', admin.site.urls),
]

asteroïd/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.dates, name="dates"),
    path('results', views.results, name='results'),
]

asteroïd/models.py
from django.db import models

# Create your models here.
from django.db import models


# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date = models.DateTimeField('date published')
#     def __str__(self):
#         return self.question_text

# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)
#     def __str__(self):
#         return self.choice_text

asteroïd/forms.py
from django import forms

class DatesForm(forms.Form):
    start_date = forms.DateField(label="Start date",input_formats=['%d/%m/%Y'], required=True)
    end_date = forms.DateField(label="End date",input_formats=['%d/%m/%Y'], required=True,)

asteroïd/views.py
from datetime import datetime
from django.http import HttpResponse
from django.http import HttpResponseRedirect

from django.template import loader
from django.shortcuts import get_object_or_404, render
import requests

from .forms import DatesForm
from .utils.functions import formatDate, get_all_days, passages
from .utils.constants import api_key

def results(request):
    return render(request,'asteroïd/results.html')

def dates(request):
    if request.method == 'POST':
        form = DatesForm(request.POST)
        
        if form.is_valid():
            start_date = formatDate(form.cleaned_data['start_date'])
            end_date = formatDate(form.cleaned_data['end_date'])
            all_days = get_all_days(form.cleaned_data['start_date'],form.cleaned_data['end_date'])

            if len(all_days) < 9:
                search_api_url = 'https://api.nasa.gov/neo/rest/v1/feed?start_date='+start_date+'&end_date='+end_date+'&api_key='+api_key
                response = requests.get(search_api_url)

                responses = []

                for i in range(len(all_days)):
                    responses += response.json()['near_earth_objects'][all_days[i]]
                
                infos = []
                for i in range(len(responses)):
                    # On lance une requête pour chaque astéroïde pour connaître son suivant et précédents passages
                    self_response = requests.get(responses[i]['links']['self']).json()
                    
                    ast_passages = passages(self_response,responses[i]['close_approach_data'][0]['close_approach_date'])

                    # Pour la taille estimée : moyenne entre le min et le max
                    infos.append(
                        {
                            'name':responses[i]['name'],
                            'estimated_diameter':(responses[i]['estimated_diameter']['kilometers']['estimated_diameter_max']+responses[i]['estimated_diameter']['kilometers']['estimated_diameter_min'])/2,
                            'distance':responses[i]['close_approach_data'][0]['miss_distance']['kilometers'],
                            'next_passage':ast_passages['next'],
                            'lasts_passages':ast_passages['lasts']
                        })
                
                context = {
                    'start_date':form.cleaned_data['start_date'],
                    'end_date':form.cleaned_data['end_date'],
                    'response':responses,
                    'infos':infos,
                    'days':all_days
                }
                # redirect to a new URL:
                return render(request,'asteroïd/results.html',context)

            else:
                return render(request, 'asteroïd/dates.html', {'form': form,'error':"Time window must not be longer than 7 days"})
    # if a GET (or any other method) we'll create a blank form
    else:
        form = DatesForm()

    return render(request, 'asteroïd/dates.html', {'form': form})

asteroïd/templates/asteroïd/dates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dates</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
    <script>
        $(function () {
          $("#id_start_date").datepicker({
            format:'dd/mm/yyyy',
          });
          $("#id_end_date").datepicker({
            format:'dd/mm/yyyy',
          });
          $("label").css({'color':'white','margin-bottom':'5px'});
          $("#id_start_date").css({"margin-bottom":"20px","border-radius":"5px"});
          $("#id_end_date").css({"margin-bottom":"30px","border-radius":"5px"})
        });
      </script>
</head>

<body style="background:#31078B;font-family:Century Gothic;display:flex;flex-direction:column;justify-content:center;align-items:center;height:98vh">
    <h1 style="color:#87EBC7">Asteroïd Scanner</h1>
    <img style="width:100px;height:auto;margin-bottom:50px" src="https://gpm.nasa.gov/sites/default/files/document_files/NASA-Logo-Large.png" alt="nasa logo"/>
    <form method="post" style="display:flex;flex-direction:column;align-items:center">
        {% csrf_token %}
        {{ form }}
        <input id="submit" type="submit" value="Go !" style="background-color:#87EBC7;border-radius:10px;font-family:Century Gothic;padding:5px;font-weight:bold;width:80px;border:none">
    </form>
    {% if error %}
        <p style="color:#C828CB">{{error}}</p>
    {% endif %}
</body>
</html>

asteroïd/templates/asteroïd/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
</head>
<body style="background:#31078B;font-family:Century Gothic;display:flex;flex-direction:column;justify-content:center;align-items:center">
    <h1 style="color:#87EBC7">Asteroïd Scanner</h1>
    <p style="color:white">{% if start_date == end_date %} {{start_date}} {% else %}From {{start_date}} to {{end_date}} {% endif %}</p>
    <a href="/asteroïd/" style="color:#C828CB;text-decoration:none;margin-bottom:30px">Return to dates</a>
    <div style="width:80%;max-width:500px">
    {% for info in infos %}
        <div class="item" style="cursor:pointer;border-width:1px;border-color:black;border-radius:5px;background-color:#87EBC7;margin:10px;padding:20px">
            <h2 style="font-weight:bold;margin:0">
                ☄️ {{ info.name }}
            </h2>
            <p><strong>Estimated diameter : </strong>{{ info.estimated_diameter }} km</p>
            <p><strong>Distance : </strong>{{ info.distance }} km</p>
            <p style="margin-bottom:0px"><strong>Next passage : </strong>{{ info.next_passage }}</p>
            <div class="lasts">
                <p><strong>Lasts passages : </strong></p>
                <ul>
                {% for lasts in info.lasts_passages %}
                    <li style="margin:5px">
                        <strong>Date :</strong> {{lasts.date}} <br/>
                        <strong>Distance :</strong> {{lasts.distance}} km
                    </li>
                {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}
    </div>
    <script>
        $(".lasts").hide();
        $(".item").click(function(){
            if($(this).is("#slided")){
                $(this).removeAttr("id")
                $(this).children(".lasts").slideUp();
            } else {
                $(this).attr("id","slided");
                $(this).children(".lasts").slideDown();
            }
        });
    </script>
</body>
</html>